#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.3 on Wed Jan 14 07:37:18 2009
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx qw[:everything];
use strict;
1;

package main;

use WxBuildWin;


unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $main = WxBuildWin->new();

	$app->SetTopWindow($main);
	$main->Show(1);
	$app->MainLoop();
}
