#!/usr/bin/perl -w -- 
# generated by wxGlade 0.6.3 on Fri Apr 10 21:07:36 2009
# To get wxPerl visit http://wxPerl.sourceforge.net/

use strict;

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MyFrame::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{panel_2} = Wx::Panel->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{panel_1} = Wx::Panel->new($self, -1, wxDefaultPosition, wxDefaultSize, );
	$self->{button_1} = Wx::Button->new($self->{panel_2}, -1, "button_1");

	$self->__set_properties();
	$self->__do_layout();

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MyFrame::__set_properties

	$self->SetTitle("frame_1");
	$self->{panel_1}->SetMinSize(Wx::Size->new(250, 270));
	$self->{panel_1}->SetBackgroundColour(Wx::Colour->new(69, 255, 143));

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MyFrame::__do_layout

	$self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
	$self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
	$self->{sizer_2}->Add($self->{panel_1}, 1, wxEXPAND, 0);
	$self->{sizer_3}->Add($self->{button_1}, 0, 0, 0);
	$self->{panel_2}->SetSizer($self->{sizer_3});
	$self->{sizer_2}->Add($self->{panel_2}, 0, wxEXPAND, 0);
	$self->{sizer_1}->Add($self->{sizer_2}, 1, wxEXPAND, 0);
	$self->SetSizer($self->{sizer_1});
	$self->{sizer_1}->Fit($self);
	$self->Layout();

# end wxGlade
}

# end of class MyFrame

1;

1;

package main;

unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $frame_1 = MyFrame->new();

	$app->SetTopWindow($frame_1);
	$frame_1->Show(1);
	$app->MainLoop();
}
